configured_endpoints: 13
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/solver-ai%2Fsolver-api-fdedda08e2a83d38c26ba2ac6ddf3672afc2ca9a4919b5c89b41f5163bd77e9e.yml
openapi_spec_hash: 3866ce3ec61b3a70740e9f8e96fe5d68
config_hash: dcd851b9fb769f60c6405bffdda2cb47
